---
- hosts: webservers
  become: true
  tasks:
     - name: Instalando servidores web
       apt: name={{item}} state=present update_cache=yes
       with_items:
          - apache2
          - libapache2-mod-wsgi
          - python-pip
          - python-virtualenv
            
     - name: Garante que o apache seja iniciando
       service: name=apache2 state=started enabled=yes
              
     - name: Garante que mod_wsgi esta habilitado
       apache2_module: state=present  name=wsgi
       notify: restart apache

     - name: copia a pasta app para o servidor
       copy: src=templates/app/ dest=/var/www/app mode=0755
       notify: restart apache
    
     - name: copia o VirtualHost para o servidor
       copy: src=templates/conf/virtualhost dest=/etc/apache2/sites-available/app.conf mode=0755
       notify: restart apache
                    
  handlers:
     - name: restart apache
       service: name=apache2 state=restarted
      